<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Favorite Restaurant</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body class="container-fluid">
        <header>
            <a><img src="assets/logo.jpeg"/></a>
        </header>

    <?php
    session_start(); 

    if($route === "connexion")
    {
        require "templates/connexion.phtml";
    }
    else if($route === "inscription")
    {
        require "templates/inscription.phtml";
    }
    else if($route === "recommanded")
    {
        require "templates/recommanded.phtml";
    }
    else if($route === "list_resto" || isset($_SESSION["email"]))
    {
        require "templates/list_resto.phtml";
    }
    else
    {
        require "templates/connexion.phtml";
    }

    ?>
    </body>
</html>