<section class="container">
    <h1>Connexion</h1>
    <form id="loginForm" action="logic/login.php" method="POST">
        <label for="email">Email</label>
        <input type="text" id="email" name="email" required>

        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Se connecter</button>
          <?php
            if (isset($_GET["password"]) && $_GET["password"] === "false") {
                echo "<p class='error'>Wrong Password</p>";
            }
        ?>
        <?php
            if (isset($_GET["email"]) && $_GET["email"] === "false") {
                echo "<p class='error'>Email doesnt exist</p>";
            }
        ?>
    </form>
    <form>
    <a href="index.php?route=inscription">Vous n'êtes pas encore inscrit ?</a>
    </form>
</section>
