<?php

$password = $_SESSION['password'];

$hash = password_hash($password, PASSWORD_DEFAULT);



?>

<main class="container">
    <h1>
        Inscription
    </h1>
    <form class="mt-5" action="logic/create-user.php" method ="post">
        <fieldset>
            <label for="email" class="form-label">Email</label>
            <input type="email" id="email" name="email" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" id="password" name="password" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="firstName" class="form-label">Prénom</label>
            <input type="text" id="firstName" name="firstName" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="lastName" class="form-label">Nom</label>
            <input type="text" id="lastName" name="lastName" class="form-control" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary" name = "envoi">Sauvegarder</button>
    </form>
</main>