<main>
    <h1>
        Inscription
    </h1>
    <form method="POST" action="logic/create_user.php">
        <fieldset>
            <label for="email" >Email</label>
            <input type="email" id="email" name="email"  />
            <?php
            if (isset($_GET["email"]) && $_GET["email"] === "set") {
                echo "<p class='error'>EMAIL ALREADY EXIST</p>";
            }
        ?>
        </fieldset>
        <fieldset>
            <label for="password" >Mot de passe</label>
            <input type="password" id="password" name="password"  require/>
        </fieldset>
        <fieldset>
            <label for="verifPassword">Verifier votre mot de passe</label>
            <input type="password" id="verifPassword" name="verifPassword"  />
            <?php
            if (isset($_GET["password"]) && $_GET["password"] === "false") {
                echo "<p class='error'> Password dosnt match</p>";
            }
        ?>
        </fieldset>
        <fieldset>
            <label for="firstName" >Prénom</label>
            <input type="text" id="firstName" name="firstName"/>
        </fieldset>
        <fieldset>
            <label for="lastName" class="form-label">Nom</label>
            <input type="text" id="lastName" name="lastName"/>
        </fieldset>
        <button type="submit">S'enregistrer</button>
    </form>
</main>