<?php
$query = $db->prepare("SELECT * FROM restaurants");
//$parameters = []
$query->execute(/*$parameters*/);
$listResto = $query->fetchAll(PDO::FETCH_ASSOC);
?>

<?php 

$query = $db->prepare("SELECT * FROM restaurants 
                        JOIN recommanded ON restaurants.id = recommanded.restaurant_id 
                        JOIN users ON users.id = recommanded.user_id WHERE users.id = :id");
$parameters = [ 'id' => $_SESSION["id"] ];
$query->execute($parameters);
$recommanded = $query->fetchAll(PDO::FETCH_ASSOC);
?>
<?php
if (isset($_SESSION["id"])) {
    foreach ($listResto as $list) { ?>
        <article class="restaurants">
            <h3><?= $list["name"] ?></h3>
            <p><?= $list["categorie"] ?></p>
            <p><?= $list["location"] ?></p>
            <img src="<?= $list["photo"] ?>" alt="photo <?= $list["name"] ?>" />
            
            <?php 
            $isRecommended = false;
            
            if ($recommanded) {
                foreach ($recommanded as $recommand) {
                    if ($list["id"] === $recommand['restaurant_id']) {
                        $isRecommended = true;
                        break;
                    }
                }
            }
            
            if ($isRecommended) { ?>
                <form action='logic/dislike.php' method="POST">
                    <input type='hidden' id="user_id" name="user_id" value='<?= $_SESSION['id'] ?>'>
                    <input type='hidden' id="restaurant_id" name="restaurant_id" value=<?= $list['id'] ?>>
                    <button class="btn"><i class="fa-regular fa-thumbs-down"></i></button>
                </form>
            <?php } else { ?>
                <form action='logic/like.php' method="POST">
                    <input type='hidden' id="user_id" name="user_id" value='<?= $_SESSION['id'] ?>'>
                    <input type='hidden' id="restaurant_id" name="restaurant_id" value=<?= $list['id'] ?>>
                    <button class="btn"><i class="fa-regular fa-thumbs-up"></i></button>
                </form>
            <?php } ?>

            <form action='templates/details.phtml' method="POST">
                <input type='hidden' id="restaurant_id" name="restaurant_id" value=<?= $list['id'] ?>>
                <button class="btn">En savoir plus</button>
            </form>
        </article>
<?php
    }
} else {
    header("Location: index.php?route=list_resto");
}
?>
